### ISSUE TITLE
Tooltip breaking in v2.2.3

### ISSUE THREAD

**Issue by althonos** [BioComputingUP/feature-viewer-typescript#13]
Hi!

I tried updating to `v2.2.3` but it seems that @marnec code additions broke the tooltip handling. I reverted back to `v2.2.0` and it worked again. Basically, the tooltip will not render transparently on top of the SVG, it will just appear before it in the document.  

Here is what I normally get with the cursor on the `TIGR03150` feature:

![tooltip](https://user-images.githubusercontent.com/8660647/97344821-8ec82680-1889-11eb-9f9c-aa99ea8f37f2.png)

Here is what I get after updating to `v2.2.3` (the top part disappears when the mouse is moved out, and the SVG is shifted upwards to its normal location afterwards):

![tooltip2](https://user-images.githubusercontent.com/8660647/97345158-08601480-188a-11eb-913a-4e79f49d1827.png)

**Comment by althonos** [comment]
From what I understood, this is due to the `fv.scss` file not being included by default after update, maybe it's a webpack issue on my end, but I was able to fix this my manually adding `features-viewer-typescript/assets/fv.scss` to my webpack exports.

**Comment by Lisanna** [comment]
Indeed, this is not due to @marnec changes but to a choice I did. 
I could import the css directly in the library, but if I do so there is no way neither in webpack nor in angular cli for the user to choose the order of the imported css modules, i.e. their prioritization. 
Use case: I have an angular app using the Feature-Viewer and some customized FV styles and I want them to overwrite the FV ones. In this case, I will import in my `angular.json` file, in styles, first the FV css and then my customized one. 
Is this clear? Would you solve this issue differently?

**Comment by althonos** [comment]
Fine by me! I was puzzled at first when upgrading broke my website, but now I understand the reason you changed that, and that it's something I need to do on my end. I can just load the `fv.scss` using the webpack `sass-loader` and it works like a charm.
